{% set name = "pyseaweed" %}
{% set version = "1.0.2" %}
{% set sha256 = "fc14e238e0a4735a07b073b3e13234803b91d6be769a2ea30c25f4e4149c129f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - six
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyseaweed
    - pyseaweed.weed

about:
  home: https://github.com/utek/pyseaweed
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python client to WeedFS'

  description: |
    SeaweedFS is a simple and highly scalable distributed file system. There
    are two objectives: to store billions of files! to serve the files fast!
    Instead of supporting full POSIX file system semantics, SeaweedFS choose to
    implement only a key~file mapping. Similar to the word "NoSQL", you can
    call it as "NoFS".
  dev_url: https://github.com/utek/pyseaweed

extra:
  recipe-maintainers:
    - frol
