# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Bzub57z0TNpo7dLoWFejXkGcKQZsmB136qc/JlUZcJAJIOBp7lDosNwOkny6/wHIRbgnwv6fheZyk0DwpdbsVmITF/ZeHnD7Pvx1ogg5A/XxXimh6wrTQMGIWp+WpufBRxap5Q/RnqnHuNReC1MXg9VQpevgswCkh/n0m6AYMwuP0KM2jGZqZayRpBWgtL0/d/YidKRRJvC4CEYd+chVH/14Y2MMMBazXwxGoCWu3K06ZC7hM+zdnbbnis0yPu5YtZGhuL/SHGGwX7BBoVIRJnc6ONxw7do3QPnsxKOnTm/yq4qmBjlq4DVitf7Oyj3R6nMlQxX2rmFZEDwmLEOjNIG64hRPG2LX14pH55BW4ivaArzeXWChlnMg7jy/LnmiFihaUTdrKIDVoPzqB8G5ApghcYjv4jA68fgGQ4GzGaZZQq4CFOI6JjKKypTAkzVb4WvOJcDhw3ve5aIZY4Fif4/LzrPHNYWNdiiKgmf/+keQsUKT59Va1xPlnYHr4jlyESgqNe/k3I0C34eIpX8vFCRFXbyUPY9TjYXWxOiuMpfaBd5rfuU1n78UPlkQ1AD+8h85vGIorLEUG75xOMMkiHgV2PSCIaWsj6rB0OSUDUcaAj3WFDl8jc/idIpZUxCgy6rCCG7bdQ1r1AfN/EJ5lxErlRBr9apu6jlwoZQAiBw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
