travis:
  secure:
    BINSTAR_TOKEN: e1LZczqKezyIL/LaKz72j9f7BPfriA5ihg/hstIqpEil01nTok7z8MXjn6q8IuiOpREwyDFMmlbTnXxBtQin44cRkVaTN1HTf0CcOwBqiwVaHkOK2DepvG132poDSYFUBR+/B/nIqOsdwjU2hgx6vogiJziBAdGmQ69jAC6wMRTBC5SUNEX5xs+bOuknHgHmWFbHJxFtoMjtQ/m9q6g9qGWFUMLkXUUa5vgCia15zKr8obTcdnsJjHWMCuIs4laGTX01kz1mLkRfQUaCaY0adCUdVN9faI/2J3wgjSheB4P+ODcbHLr+v1FyWD7Ii2mqCEz+AnHpt36is6wzTYDMkBF/9242PtnrXpvSJigYz5zm6pY+4KZHV9CbmDwOz4yqbUjxObdLdz5l/pxZ0Xn0JBvzhQ762AppLB8696WpTA4Bz9bgMwqoMFclwon/rczXykgXhA2T28PxETWm/YQnWng+4qnh8hG9VeoDflrgzr/xNVditIQ2yryRjSvQc1x39cHyfSZqNAEnH0981pBiL9BLF3wu0DjmdnNmFIcQ6q53wuQcwSRF01bdTlu1jevoq+iq1Fj3i1CLsZcdX0FakWhZbBM2KMPMXH+K2VlcI82tHw+nQyrdNVb272GFzSSeiuGvPwq07cMugEV1F/unHcDPULyCSLfrUeEwQwIqyz4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
