travis:
  secure:
    BINSTAR_TOKEN: Bzub57z0TNpo7dLoWFejXkGcKQZsmB136qc/JlUZcJAJIOBp7lDosNwOkny6/wHIRbgnwv6fheZyk0DwpdbsVmITF/ZeHnD7Pvx1ogg5A/XxXimh6wrTQMGIWp+WpufBRxap5Q/RnqnHuNReC1MXg9VQpevgswCkh/n0m6AYMwuP0KM2jGZqZayRpBWgtL0/d/YidKRRJvC4CEYd+chVH/14Y2MMMBazXwxGoCWu3K06ZC7hM+zdnbbnis0yPu5YtZGhuL/SHGGwX7BBoVIRJnc6ONxw7do3QPnsxKOnTm/yq4qmBjlq4DVitf7Oyj3R6nMlQxX2rmFZEDwmLEOjNIG64hRPG2LX14pH55BW4ivaArzeXWChlnMg7jy/LnmiFihaUTdrKIDVoPzqB8G5ApghcYjv4jA68fgGQ4GzGaZZQq4CFOI6JjKKypTAkzVb4WvOJcDhw3ve5aIZY4Fif4/LzrPHNYWNdiiKgmf/+keQsUKT59Va1xPlnYHr4jlyESgqNe/k3I0C34eIpX8vFCRFXbyUPY9TjYXWxOiuMpfaBd5rfuU1n78UPlkQ1AD+8h85vGIorLEUG75xOMMkiHgV2PSCIaWsj6rB0OSUDUcaAj3WFDl8jc/idIpZUxCgy6rCCG7bdQ1r1AfN/EJ5lxErlRBr9apu6jlwoZQAiBw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
